/**
 * Saytdagi barcha rasm va videolar ro'yxati.
 *
 * BU FAYL QO'LDA EMAS, komponentlardagi manzillardan generatsiya qilingan.
 * Har bir yozuvning `def` maydoni — koddagi standart manzil. Admin paneldan
 * o'zgartirilsa, yangi manzil `data/media.json` ga yoziladi va `def`
 * o'rniga ishlatiladi. Yozuv o'chirilsa yana `def` ga qaytadi.
 *
 * `id` — barqaror kalit; uni o'zgartirish admin o'zgarishlarini uzib qo'yadi.
 */

export type MediaType = "image" | "video";

export interface MediaItem {
  id: string;
  label: string;
  /** lib/page-map.ts dagi sahifa kaliti */
  page: string;
  block: string;
  type: MediaType;
  /** Koddagi standart manzil */
  def: string;
}

export const MEDIA: MediaItem[] = [
  {
    id: "bosh.hero.poster",
    label: "Bosh ekran — video o'rnidagi rasm",
    page: "bosh",
    block: "Bosh ekran",
    type: "image",
    def: "/images/1.jpg",
  },
  {
    id: "rahbariyat.cover",
    label: "Jamoa oynasi muqovasi",
    page: "rahbariyat",
    block: "Muqova",
    type: "image",
    def: "/images/site/cl-IMG_4429_copy_dqhz5y.jpg",
  },
  {
    id: "rahbariyat.avatar.rustamjon",
    label: "Rustamjon — surati",
    page: "rahbariyat",
    block: "Jamoa suratlari",
    type: "image",
    def: "/team/ceo.jpg",
  },
  {
    id: "rahbariyat.avatar.alisher",
    label: "Alisher — surati",
    page: "rahbariyat",
    block: "Jamoa suratlari",
    type: "image",
    def: "/team/marketolog.jpg",
  },
  {
    id: "rahbariyat.avatar.abdulloh",
    label: "Abdulloh — surati",
    page: "rahbariyat",
    block: "Jamoa suratlari",
    type: "image",
    def: "",
  },
  {
    id: "rahbariyat.avatar.bobgulbaxor",
    label: "Bobgulbaxor — surati",
    page: "rahbariyat",
    block: "Jamoa suratlari",
    type: "image",
    def: "",
  },
  {
    id: "rahbariyat.avatar.nafosat",
    label: "Nafosat — surati",
    page: "rahbariyat",
    block: "Jamoa suratlari",
    type: "image",
    def: "",
  },
  {
    id: "rahbariyat.avatar.dilnoza",
    label: "Dilnoza — surati",
    page: "rahbariyat",
    block: "Jamoa suratlari",
    type: "image",
    def: "",
  },
  {
    id: "rahbariyat.avatar.sardor",
    label: "Sardor — surati",
    page: "rahbariyat",
    block: "Jamoa suratlari",
    type: "image",
    def: "",
  },
  {
    id: "umumiy.logo",
    label: "Sayt logotipi",
    page: "umumiy",
    block: "Logotip",
    type: "image",
    def: "/images/logo.png",
  },
  {
    id: "bosh.hero.video",
    label: "Bosh ekran fon videosi",
    page: "bosh",
    block: "Bosh ekran",
    type: "video",
    def: "",
  },
  {
    id: "bosh.about.background",
    label: "«Biz haqimizda» fon rasmi",
    page: "bosh",
    block: "Biz haqimizda",
    type: "image",
    def: "/images/photo_2026-04-04_10-35-29.jpg",
  },
  {
    id: "bosh.about.slide.0",
    label: "«Biz haqimizda» slayd 1",
    page: "bosh",
    block: "Biz haqimizda",
    type: "image",
    def: "/images/8.jpg",
  },
  {
    id: "bosh.about.slide.1",
    label: "«Biz haqimizda» slayd 2",
    page: "bosh",
    block: "Biz haqimizda",
    type: "image",
    def: "/images/3.jpg",
  },
  {
    id: "bosh.about.slide.2",
    label: "«Biz haqimizda» slayd 3",
    page: "bosh",
    block: "Biz haqimizda",
    type: "image",
    def: "/images/24.jpg",
  },
  {
    id: "bosh.about.slide.3",
    label: "«Biz haqimizda» slayd 4",
    page: "bosh",
    block: "Biz haqimizda",
    type: "image",
    def: "/images/25.jpg",
  },
  {
    id: "bosh.about.slide.4",
    label: "«Biz haqimizda» slayd 5",
    page: "bosh",
    block: "Biz haqimizda",
    type: "image",
    def: "/images/27.jpg",
  },
  {
    id: "bosh.about.slide.5",
    label: "«Biz haqimizda» slayd 6",
    page: "bosh",
    block: "Biz haqimizda",
    type: "image",
    def: "/images/photo_2026-04-04_10-35-25.jpg",
  },
  {
    id: "xizmatlar.engineering.0",
    label: "Injiniring rasmi 1",
    page: "xizmatlar",
    block: "Injiniring",
    type: "image",
    def: "/images/8.jpg",
  },
  {
    id: "xizmatlar.engineering.1",
    label: "Injiniring rasmi 2",
    page: "xizmatlar",
    block: "Injiniring",
    type: "image",
    def: "/images/3.jpg",
  },
  {
    id: "xizmatlar.equipment.0",
    label: "Jihozlar rasmi 1",
    page: "xizmatlar",
    block: "Jihozlar",
    type: "image",
    def: "/images/site/jihoz-shkaf.jpg",
  },
  {
    id: "xizmatlar.equipment.1",
    label: "Jihozlar rasmi 2",
    page: "xizmatlar",
    block: "Jihozlar",
    type: "image",
    def: "/images/site/jihoz-motor.jpg",
  },
  {
    id: "xizmatlar.equipment.2",
    label: "Jihozlar rasmi 3",
    page: "xizmatlar",
    block: "Jihozlar",
    type: "image",
    def: "/images/site/jihoz-nasos.jpg",
  },
  {
    id: "xizmatlar.equipment.3",
    label: "Jihozlar rasmi 4",
    page: "xizmatlar",
    block: "Jihozlar",
    type: "image",
    def: "/images/site/jihoz-sovutish.jpg",
  },
  {
    id: "xizmatlar.equipment.4",
    label: "Jihozlar rasmi 5",
    page: "xizmatlar",
    block: "Jihozlar",
    type: "image",
    def: "/images/site/jihoz-fan.jpg",
  },
  {
    id: "loyihalar.item1.0",
    label: "1-loyiha, rasm 1",
    page: "loyihalar",
    block: "1-loyiha",
    type: "image",
    def: "/images/site/cl-IMG_4397_copy_fymoco.jpg",
  },
  {
    id: "loyihalar.item1.1",
    label: "1-loyiha, rasm 2",
    page: "loyihalar",
    block: "1-loyiha",
    type: "image",
    def: "/images/site/cl-2_nqvejm.jpg",
  },
  {
    id: "loyihalar.item1.2",
    label: "1-loyiha, rasm 3",
    page: "loyihalar",
    block: "1-loyiha",
    type: "image",
    def: "/images/site/cl-IMG_4392_copy_xwrtpy.jpg",
  },
  {
    id: "loyihalar.item1.3",
    label: "1-loyiha, rasm 4",
    page: "loyihalar",
    block: "1-loyiha",
    type: "image",
    def: "/images/site/cl-IMG_4429_copy_dqhz5y.jpg",
  },
  {
    id: "loyihalar.item1.4",
    label: "1-loyiha, rasm 5",
    page: "loyihalar",
    block: "1-loyiha",
    type: "image",
    def: "/images/site/cl-IMG_4429_copy_dqhz5y.jpg",
  },
  {
    id: "loyihalar.item2.0",
    label: "2-loyiha, rasm 1",
    page: "loyihalar",
    block: "2-loyiha",
    type: "image",
    def: "/images/site/cl-IMG_4429_copy_dqhz5y.jpg",
  },
  {
    id: "loyihalar.item2.1",
    label: "2-loyiha, rasm 2",
    page: "loyihalar",
    block: "2-loyiha",
    type: "image",
    def: "/images/site/cl-IMG_1075_rrylu1.jpg",
  },
  {
    id: "loyihalar.item2.2",
    label: "2-loyiha, rasm 3",
    page: "loyihalar",
    block: "2-loyiha",
    type: "image",
    def: "/images/site/cl-IMG_3535_zs9roq.jpg",
  },
  {
    id: "loyihalar.item2.3",
    label: "2-loyiha, rasm 4",
    page: "loyihalar",
    block: "2-loyiha",
    type: "image",
    def: "/images/25.jpg",
  },
  {
    id: "loyihalar.item2.4",
    label: "2-loyiha, rasm 5",
    page: "loyihalar",
    block: "2-loyiha",
    type: "image",
    def: "/images/27.jpg",
  },
  {
    id: "loyihalar.item3.0",
    label: "3-loyiha, rasm 1",
    page: "loyihalar",
    block: "3-loyiha",
    type: "image",
    def: "/images/site/qulupnay-issiqxona.jpg",
  },
  {
    id: "loyihalar.item3.1",
    label: "3-loyiha, rasm 2",
    page: "loyihalar",
    block: "3-loyiha",
    type: "image",
    def: "/images/site/ekin-qulupnay.jpg",
  },
  {
    id: "loyihalar.item3.2",
    label: "3-loyiha, rasm 3",
    page: "loyihalar",
    block: "3-loyiha",
    type: "image",
    def: "/images/site/prezident-issiqxona.jpg",
  },
  {
    id: "loyihalar.item3.3",
    label: "3-loyiha, rasm 4",
    page: "loyihalar",
    block: "3-loyiha",
    type: "image",
    def: "/images/site/issiqxona-ichi.jpg",
  },
  {
    id: "loyihalar.item4.0",
    label: "4-loyiha, rasm 1",
    page: "loyihalar",
    block: "4-loyiha",
    type: "image",
    def: "/images/site/cl-IMG_3535_zs9roq.jpg",
  },
  {
    id: "loyihalar.item4.1",
    label: "4-loyiha, rasm 2",
    page: "loyihalar",
    block: "4-loyiha",
    type: "image",
    def: "/images/site/cl-IMG_0976_kkvp42.jpg",
  },
  {
    id: "loyihalar.item4.2",
    label: "4-loyiha, rasm 3",
    page: "loyihalar",
    block: "4-loyiha",
    type: "image",
    def: "/images/site/cl-IMG_1052_qr8w62.jpg",
  },
  {
    id: "loyihalar.item4.3",
    label: "4-loyiha, rasm 4",
    page: "loyihalar",
    block: "4-loyiha",
    type: "image",
    def: "/images/site/cl-IMG_0980_adj1rq.jpg",
  },
  {
    id: "loyihalar.item4.4",
    label: "4-loyiha, rasm 5",
    page: "loyihalar",
    block: "4-loyiha",
    type: "image",
    def: "/images/1.jpg",
  },
  {
    id: "loyihalar.item5.0",
    label: "5-loyiha, rasm 1",
    page: "loyihalar",
    block: "5-loyiha",
    type: "image",
    def: "/images/2.jpg",
  },
  {
    id: "loyihalar.item5.1",
    label: "5-loyiha, rasm 2",
    page: "loyihalar",
    block: "5-loyiha",
    type: "image",
    def: "/images/3.jpg",
  },
  {
    id: "loyihalar.item6.0",
    label: "6-loyiha, rasm 1",
    page: "loyihalar",
    block: "6-loyiha",
    type: "image",
    def: "/images/site/cl-IMG_1075_rrylu1.jpg",
  },
  {
    id: "loyihalar.item6.1",
    label: "6-loyiha, rasm 2",
    page: "loyihalar",
    block: "6-loyiha",
    type: "image",
    def: "/images/site/cl-IMG_3535_zs9roq.jpg",
  },
  {
    id: "loyihalar.item6.2",
    label: "6-loyiha, rasm 3",
    page: "loyihalar",
    block: "6-loyiha",
    type: "image",
    def: "/images/site/cl-IMG_0976_kkvp42.jpg",
  },
  {
    id: "loyihalar.item6.3",
    label: "6-loyiha, rasm 4",
    page: "loyihalar",
    block: "6-loyiha",
    type: "image",
    def: "/images/site/cl-IMG_1052_qr8w62.jpg",
  },
  {
    id: "loyihalar.item6.4",
    label: "6-loyiha, rasm 5",
    page: "loyihalar",
    block: "6-loyiha",
    type: "image",
    def: "/images/site/cl-IMG_0980_adj1rq.jpg",
  },
  {
    id: "jixozlar.tech.0",
    label: "Isitish rasmi",
    page: "jixozlar",
    block: "Texnologiya kartalari",
    type: "image",
    def: "/images/site/jihoz-isitish.jpg",
  },
  {
    id: "jixozlar.tech.1",
    label: "Ventilyatsiya rasmi",
    page: "jixozlar",
    block: "Texnologiya kartalari",
    type: "image",
    def: "/images/site/jihoz-ventilyatsiya.jpg",
  },
  {
    id: "jixozlar.tech.2",
    label: "Stellaj rasmi",
    page: "jixozlar",
    block: "Texnologiya kartalari",
    type: "image",
    def: "/images/site/jihoz-stellaj.jpg",
  },
  {
    id: "jixozlar.tech.3",
    label: "Sug'orish rasmi",
    page: "jixozlar",
    block: "Texnologiya kartalari",
    type: "image",
    def: "/images/site/jihoz-sugorish.jpg",
  },
  {
    id: "jixozlar.tech.4",
    label: "Avtomatlashtirish rasmi",
    page: "jixozlar",
    block: "Texnologiya kartalari",
    type: "image",
    def: "/images/site/jihoz-avtomatika.jpg",
  },
  {
    id: "issiqxona.vertical.0",
    label: "Vertikal issiqxona, rasm 1",
    page: "issiqxona-turlari",
    block: "Vertikal issiqxona",
    type: "image",
    def: "/images/site/cl-IMG_0980_adj1rq.jpg",
  },
  {
    id: "issiqxona.vertical.1",
    label: "Vertikal issiqxona, rasm 2",
    page: "issiqxona-turlari",
    block: "Vertikal issiqxona",
    type: "image",
    def: "/images/1.jpg",
  },
  {
    id: "issiqxona.vertical.2",
    label: "Vertikal issiqxona, rasm 3",
    page: "issiqxona-turlari",
    block: "Vertikal issiqxona",
    type: "image",
    def: "/images/2.jpg",
  },
  {
    id: "issiqxona.vertical.3",
    label: "Vertikal issiqxona, rasm 4",
    page: "issiqxona-turlari",
    block: "Vertikal issiqxona",
    type: "image",
    def: "/images/3.jpg",
  },
  {
    id: "issiqxona.vertical.4",
    label: "Vertikal issiqxona, rasm 5",
    page: "issiqxona-turlari",
    block: "Vertikal issiqxona",
    type: "image",
    def: "/images/4.jpg",
  },
  {
    id: "issiqxona.vertical.5",
    label: "Vertikal issiqxona, rasm 6",
    page: "issiqxona-turlari",
    block: "Vertikal issiqxona",
    type: "image",
    def: "/images/7.jpg",
  },
  {
    id: "issiqxona.vertical.6",
    label: "Vertikal issiqxona, rasm 7",
    page: "issiqxona-turlari",
    block: "Vertikal issiqxona",
    type: "image",
    def: "/images/8.jpg",
  },
  {
    id: "issiqxona.mini.0",
    label: "Mini issiqxona, rasm 1",
    page: "issiqxona-turlari",
    block: "Mini issiqxona",
    type: "image",
    def: "/images/24.jpg",
  },
  {
    id: "issiqxona.mini.1",
    label: "Mini issiqxona, rasm 2",
    page: "issiqxona-turlari",
    block: "Mini issiqxona",
    type: "image",
    def: "/images/25.jpg",
  },
  {
    id: "issiqxona.mini.2",
    label: "Mini issiqxona, rasm 3",
    page: "issiqxona-turlari",
    block: "Mini issiqxona",
    type: "image",
    def: "/images/27.jpg",
  },
  {
    id: "issiqxona.oddiy.0",
    label: "Oddiy issiqxona, rasm 1",
    page: "issiqxona-turlari",
    block: "Oddiy issiqxona",
    type: "image",
    def: "/images/photo_2026-04-04_10-35-25.jpg",
  },
  {
    id: "issiqxona.oddiy.1",
    label: "Oddiy issiqxona, rasm 2",
    page: "issiqxona-turlari",
    block: "Oddiy issiqxona",
    type: "image",
    def: "/images/photo_2026-04-04_10-35-29.jpg",
  },
  {
    id: "issiqxona.oddiy.2",
    label: "Oddiy issiqxona, rasm 3",
    page: "issiqxona-turlari",
    block: "Oddiy issiqxona",
    type: "image",
    def: "/images/photo_2026-04-04_10-35-50.jpg",
  },
  {
    id: "issiqxona.oddiy.3",
    label: "Oddiy issiqxona, rasm 4",
    page: "issiqxona-turlari",
    block: "Oddiy issiqxona",
    type: "image",
    def: "/images/photo_2026-04-04_10-35-53.jpg",
  },
  {
    id: "issiqxona.oddiy.4",
    label: "Oddiy issiqxona, rasm 5",
    page: "issiqxona-turlari",
    block: "Oddiy issiqxona",
    type: "image",
    def: "/images/photo_2026-04-04_10-35-54.jpg",
  },
  {
    id: "issiqxona.gektar.0",
    label: "Gektar issiqxona, rasm 1",
    page: "issiqxona-turlari",
    block: "Gektar issiqxona",
    type: "image",
    def: "/images/photo_2026-04-04_10-35-55.jpg",
  },
  {
    id: "issiqxona.gektar.1",
    label: "Gektar issiqxona, rasm 2",
    page: "issiqxona-turlari",
    block: "Gektar issiqxona",
    type: "image",
    def: "/images/site/cl-IMG_4397_copy_fymoco.jpg",
  },
  {
    id: "issiqxona.gektar.2",
    label: "Gektar issiqxona, rasm 3",
    page: "issiqxona-turlari",
    block: "Gektar issiqxona",
    type: "image",
    def: "/images/site/cl-2_nqvejm.jpg",
  },
  {
    id: "xalqaro.project.0",
    label: "Loyiha rasmi 1",
    page: "xalqaro",
    block: "Loyiha rasmlari",
    type: "image",
    def: "/images/site/cl-IMG_4392_copy_xwrtpy.jpg",
  },
  {
    id: "xalqaro.project.1",
    label: "Loyiha rasmi 2",
    page: "xalqaro",
    block: "Loyiha rasmlari",
    type: "image",
    def: "/images/1.jpg",
  },
  {
    id: "xalqaro.project.2",
    label: "Loyiha rasmi 3",
    page: "xalqaro",
    block: "Loyiha rasmlari",
    type: "image",
    def: "/images/photo_2026-04-04_10-35-53.jpg",
  },
  {
    id: "xalqaro.project.3",
    label: "Loyiha rasmi 4",
    page: "xalqaro",
    block: "Loyiha rasmlari",
    type: "image",
    def: "/images/site/cl-2_nqvejm.jpg",
  },
  {
    id: "aloqa.background.0",
    label: "Fon slayd 1",
    page: "aloqa",
    block: "Fon rasmlari",
    type: "image",
    def: "/images/1.jpg",
  },
  {
    id: "aloqa.background.1",
    label: "Fon slayd 2",
    page: "aloqa",
    block: "Fon rasmlari",
    type: "image",
    def: "/images/2.jpg",
  },
  {
    id: "aloqa.background.2",
    label: "Fon slayd 3",
    page: "aloqa",
    block: "Fon rasmlari",
    type: "image",
    def: "/images/3.jpg",
  },
  {
    id: "aloqa.background.3",
    label: "Fon slayd 4",
    page: "aloqa",
    block: "Fon rasmlari",
    type: "image",
    def: "/images/4.jpg",
  },
  {
    id: "haqimizda.image",
    label: "Ofis / infografika rasmi",
    page: "haqimizda",
    block: "Rasm",
    type: "image",
    def: "/images/site/expo-stend.jpg",
  },
  {
    id: "gallery.1",
    label: "Sanoat issiqxonasi (№1)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/1.jpg",
  },
  {
    id: "gallery.2",
    label: "Qishloq xo'jaligi issiqxonasi (№2)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/2.jpg",
  },
  {
    id: "gallery.3",
    label: "Quyosh issiqxonasi (№3)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/3.jpg",
  },
  {
    id: "gallery.4",
    label: "Qulupnay issiqxonasi (№4)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/4.jpg",
  },
  {
    id: "gallery.5",
    label: "Raqamli ta'lim markazi (№5)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/7.jpg",
  },
  {
    id: "gallery.6",
    label: "Energetika loyihasi (№6)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/8.jpg",
  },
  {
    id: "gallery.7",
    label: "Eksport issiqxonasi (№7)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/24.jpg",
  },
  {
    id: "gallery.8",
    label: "Gidroponika issiqxonasi (№8)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/25.jpg",
  },
  {
    id: "gallery.9",
    label: "Xalqaro turizm markazi (№9)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/27.jpg",
  },
  {
    id: "gallery.10",
    label: "Prezident tashrifi (№10)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/prezident-issiqxona.jpg",
  },
  {
    id: "gallery.11",
    label: "Loyihalar ochilishi (№11)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/prezident-qatorlar.jpg",
  },
  {
    id: "gallery.12",
    label: "Prezident bilan uchrashuv (№12)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/prezident-uchrashuv.jpg",
  },
  {
    id: "gallery.13",
    label: "Memorandum imzolandi (№13)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/prezident-hujjat.jpg",
  },
  {
    id: "gallery.14",
    label: "Yangi korxona (№14)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/qulupnay-issiqxona.jpg",
  },
  {
    id: "gallery.15",
    label: "Hududni ko'rish (№15)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/prezident-qulupnay.jpg",
  },
  {
    id: "gallery.21",
    label: "Tomat issiqxonasi (№21)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/ekin-tomat.jpg",
  },
  {
    id: "gallery.22",
    label: "Bodring issiqxonasi (№22)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/ekin-bodring.jpg",
  },
  {
    id: "gallery.23",
    label: "Sabzavot issiqxonasi (№23)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/ekin-sabzavot.jpg",
  },
  {
    id: "gallery.24",
    label: "Meva issiqxonasi (№24)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/ekin-qulupnay.jpg",
  },
  {
    id: "gallery.25",
    label: "Gullar issiqxonasi (№25)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/gallery-25.jpg",
  },
  {
    id: "gallery.26",
    label: "Ziravorlar issiqxonasi (№26)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/gallery-26.jpg",
  },
  {
    id: "gallery.27",
    label: "O'simliklar issiqxonasi (№27)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/gallery-27.jpg",
  },
  {
    id: "gallery.28",
    label: "Dorivor o'simliklar issiqxonasi (№28)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/gallery-28.jpg",
  },
  {
    id: "gallery.29",
    label: "Tibbiy o'simliklar issiqxonasi (№29)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/gallery-29.jpg",
  },
  {
    id: "gallery.30",
    label: "Organik issiqxona (№30)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/gallery-30.jpg",
  },
  {
    id: "gallery.31",
    label: "Qozog'iston loyihasi (№31)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/photo_2026-04-04_10-35-50.jpg",
  },
  {
    id: "gallery.32",
    label: "Tojikiston loyihasi (№32)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/1.jpg",
  },
  {
    id: "gallery.33",
    label: "Qirg'iziston loyihasi (№33)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/photo_2026-04-04_10-35-53.jpg",
  },
  {
    id: "gallery.34",
    label: "Turkmaniston loyihasi (№34)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/photo_2026-04-04_10-35-54.jpg",
  },
  {
    id: "gallery.35",
    label: "Isitish tizimi (№35)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/jihoz-isitish.jpg",
  },
  {
    id: "gallery.36",
    label: "Ventilyatsiya (№36)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/jihoz-ventilyatsiya.jpg",
  },
  {
    id: "gallery.37",
    label: "Stelaj tizimi (№37)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/jihoz-stellaj.jpg",
  },
  {
    id: "gallery.38",
    label: "Avtomatlashtirish (№38)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/jihoz-avtomatika.jpg",
  },
  {
    id: "gallery.39",
    label: "Andijon loyihasi 1 (№39)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/cl-IMG_4429_copy_dqhz5y.jpg",
  },
  {
    id: "gallery.40",
    label: "Andijon loyihasi 2 (№40)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/cl-IMG_1075_rrylu1.jpg",
  },
  {
    id: "gallery.41",
    label: "Andijon loyihasi 3 (№41)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/cl-IMG_3535_zs9roq.jpg",
  },
  {
    id: "gallery.42",
    label: "Andijon loyihasi 4 (№42)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/25.jpg",
  },
  {
    id: "gallery.43",
    label: "Andijon loyihasi 5 (№43)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/27.jpg",
  },
  {
    id: "gallery.44",
    label: "Samarqand loyihasi 1 (№44)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/cl-IMG_0976_kkvp42.jpg",
  },
  {
    id: "gallery.45",
    label: "Samarqand loyihasi 2 (№45)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/cl-IMG_1052_qr8w62.jpg",
  },
  {
    id: "gallery.46",
    label: "Yangi loyiha (№46)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/cl-IMG_1015_jf5dqm.jpg",
  },
  {
    id: "gallery.47",
    label: "Yangi loyiha (№47)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/cl-IMG_0994_angy5l.jpg",
  },
  {
    id: "gallery.48",
    label: "Yangi loyiha (№48)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/cl-IMG_1033_akpcc1.jpg",
  },
  {
    id: "gallery.49",
    label: "Yangi loyiha (№49)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/cl-IMG_1030_dcuj82.jpg",
  },
  {
    id: "gallery.50",
    label: "Yangi loyiha (№50)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/cl-IMG_1001_vft7io.jpg",
  },
  {
    id: "gallery.51",
    label: "Yangi loyiha (№51)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/site/cl-IMG_1059_wwp8bn.jpg",
  },
];

export const MEDIA_DEFAULTS: Record<string, string> = Object.fromEntries(
  MEDIA.map((item) => [item.id, item.def]),
);
