/**
 * Saytdagi barcha rasm va videolar ro'yxati.
 *
 * BU FAYL QO'LDA EMAS, komponentlardagi manzillardan generatsiya qilingan.
 * Har bir yozuvning `def` maydoni — koddagi standart manzil. Admin paneldan
 * o'zgartirilsa, yangi manzil `data/media.json` ga yoziladi va `def`
 * o'rniga ishlatiladi. Yozuv o'chirilsa yana `def` ga qaytadi.
 *
 * `id` — barqaror kalit; uni o'zgartirish admin o'zgarishlarini uzib qo'yadi.
 */

export type MediaType = "image" | "video";

export interface MediaItem {
  id: string;
  label: string;
  /** lib/page-map.ts dagi sahifa kaliti */
  page: string;
  block: string;
  type: MediaType;
  /** Koddagi standart manzil */
  def: string;
}

export const MEDIA: MediaItem[] = [
  {
    id: "rahbariyat.avatar.rustamjon",
    label: "Rustamjon — surati",
    page: "rahbariyat",
    block: "Jamoa suratlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/c_fill,g_face,w_600,h_600/v1776668168/ChatGPT_Image_17_апр._2026_г._17_10_12_ufx3pd.png",
  },
  {
    id: "rahbariyat.avatar.alisher",
    label: "Alisher — surati",
    page: "rahbariyat",
    block: "Jamoa suratlari",
    type: "image",
    def: "/team/marketolog.jpg",
  },
  {
    id: "rahbariyat.avatar.abdulloh",
    label: "Abdulloh — surati",
    page: "rahbariyat",
    block: "Jamoa suratlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/c_fill,g_face,w_600,h_600/v1776668167/ChatGPT_Image_17_апр._2026_г._16_55_09_p4gndn.png",
  },
  {
    id: "rahbariyat.avatar.bobgulbaxor",
    label: "Bobgulbaxor — surati",
    page: "rahbariyat",
    block: "Jamoa suratlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/c_fill,g_face,w_600,h_600/v1776668169/ChatGPT_Image_17_апр._2026_г._16_39_33_ufyw96.png",
  },
  {
    id: "rahbariyat.avatar.nafosat",
    label: "Nafosat — surati",
    page: "rahbariyat",
    block: "Jamoa suratlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/c_fill,g_face,w_600,h_600/v1776668177/ChatGPT_Image_17_апр._2026_г._16_25_41_ue4kdd.png",
  },
  {
    id: "rahbariyat.avatar.dilnoza",
    label: "Dilnoza — surati",
    page: "rahbariyat",
    block: "Jamoa suratlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/c_fill,g_face,w_600,h_600/v1776668170/ChatGPT_Image_17_апр._2026_г._16_34_42_yqzxzv.png",
  },
  {
    id: "rahbariyat.avatar.sardor",
    label: "Sardor — surati",
    page: "rahbariyat",
    block: "Jamoa suratlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/c_fill,g_face,w_600,h_600/v1776668171/ChatGPT_Image_17_апр._2026_г._16_45_29_hthlyp.png",
  },
  {
    id: "umumiy.logo",
    label: "Sayt logotipi",
    page: "umumiy",
    block: "Logotip",
    type: "image",
    def: "/images/logo.png",
  },
  {
    id: "bosh.hero.video",
    label: "Bosh ekran fon videosi",
    page: "bosh",
    block: "Bosh ekran",
    type: "video",
    def: "https://res.cloudinary.com/dnqi0bdjk/video/upload/v1776668436/IMG_5977_tbxama.mp4",
  },
  {
    id: "bosh.about.background",
    label: "«Biz haqimizda» fon rasmi",
    page: "bosh",
    block: "Biz haqimizda",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469050/IMG_5189_%D0%9E%D1%80%D0%B8%D0%B3%D0%B8%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9_%D1%80%D0%B0%D0%B7%D0%BC%D0%B5%D1%80_atdoz0.jpg",
  },
  {
    id: "bosh.about.slide.0",
    label: "«Biz haqimizda» slayd 1",
    page: "bosh",
    block: "Biz haqimizda",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775567592/20201201_105521_ugdege.jpg",
  },
  {
    id: "bosh.about.slide.1",
    label: "«Biz haqimizda» slayd 2",
    page: "bosh",
    block: "Biz haqimizda",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775567918/20201201_143010_eudwpq.jpg",
  },
  {
    id: "bosh.about.slide.2",
    label: "«Biz haqimizda» slayd 3",
    page: "bosh",
    block: "Biz haqimizda",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469212/37_2_ggepkx.jpg",
  },
  {
    id: "bosh.about.slide.3",
    label: "«Biz haqimizda» slayd 4",
    page: "bosh",
    block: "Biz haqimizda",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469212/32_2_n7x8lw.jpg",
  },
  {
    id: "bosh.about.slide.4",
    label: "«Biz haqimizda» slayd 5",
    page: "bosh",
    block: "Biz haqimizda",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469212/38_shg9uf.jpg",
  },
  {
    id: "bosh.about.slide.5",
    label: "«Biz haqimizda» slayd 6",
    page: "bosh",
    block: "Biz haqimizda",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775468978/31_phdvd6.jpg",
  },
  {
    id: "xizmatlar.engineering.0",
    label: "Injiniring rasmi 1",
    page: "xizmatlar",
    block: "Injiniring",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775567592/20201201_105521_ugdege.jpg",
  },
  {
    id: "xizmatlar.engineering.1",
    label: "Injiniring rasmi 2",
    page: "xizmatlar",
    block: "Injiniring",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775567918/20201201_143010_eudwpq.jpg",
  },
  {
    id: "xizmatlar.equipment.0",
    label: "Jihozlar rasmi 1",
    page: "xizmatlar",
    block: "Jihozlar",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469176/20201201_105259_q5us00.jpg",
  },
  {
    id: "xizmatlar.equipment.1",
    label: "Jihozlar rasmi 2",
    page: "xizmatlar",
    block: "Jihozlar",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775567816/20201201_125910_t1nzq8.jpg",
  },
  {
    id: "xizmatlar.equipment.2",
    label: "Jihozlar rasmi 3",
    page: "xizmatlar",
    block: "Jihozlar",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775468983/IMG_4392_copy_xdhodo.jpg",
  },
  {
    id: "xizmatlar.equipment.3",
    label: "Jihozlar rasmi 4",
    page: "xizmatlar",
    block: "Jihozlar",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775468978/31_phdvd6.jpg",
  },
  {
    id: "xizmatlar.equipment.4",
    label: "Jihozlar rasmi 5",
    page: "xizmatlar",
    block: "Jihozlar",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775468978/IMG_3865_ygsucd.jpg",
  },
  {
    id: "loyihalar.item1.0",
    label: "1-loyiha, rasm 1",
    page: "loyihalar",
    block: "1-loyiha",
    type: "image",
    def: "https://res.cloudinary.com/duvvgqc3i/image/upload/q_auto/f_auto/v1776423881/IMG_4397_copy_fymoco.jpg",
  },
  {
    id: "loyihalar.item1.1",
    label: "1-loyiha, rasm 2",
    page: "loyihalar",
    block: "1-loyiha",
    type: "image",
    def: "https://res.cloudinary.com/duvvgqc3i/image/upload/q_auto/f_auto/v1776423899/2_nqvejm.jpg",
  },
  {
    id: "loyihalar.item1.2",
    label: "1-loyiha, rasm 3",
    page: "loyihalar",
    block: "1-loyiha",
    type: "image",
    def: "https://res.cloudinary.com/duvvgqc3i/image/upload/q_auto/f_auto/v1776423853/IMG_4392_copy_xwrtpy.jpg",
  },
  {
    id: "loyihalar.item1.3",
    label: "1-loyiha, rasm 4",
    page: "loyihalar",
    block: "1-loyiha",
    type: "image",
    def: "https://res.cloudinary.com/duvvgqc3i/image/upload/q_auto/f_auto/v1776423866/IMG_4429_copy_dqhz5y.jpg",
  },
  {
    id: "loyihalar.item1.4",
    label: "1-loyiha, rasm 5",
    page: "loyihalar",
    block: "1-loyiha",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469049/photo_2026-04-04_10-35-29_ajfw6x.jpg",
  },
  {
    id: "loyihalar.item2.0",
    label: "2-loyiha, rasm 1",
    page: "loyihalar",
    block: "2-loyiha",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775468970/21_bv62xg.jpg",
  },
  {
    id: "loyihalar.item2.1",
    label: "2-loyiha, rasm 2",
    page: "loyihalar",
    block: "2-loyiha",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775301447/22_qrawq5.jpg",
  },
  {
    id: "loyihalar.item2.2",
    label: "2-loyiha, rasm 3",
    page: "loyihalar",
    block: "2-loyiha",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469214/34_rthdcs.jpg",
  },
  {
    id: "loyihalar.item2.3",
    label: "2-loyiha, rasm 4",
    page: "loyihalar",
    block: "2-loyiha",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469212/32_2_n7x8lw.jpg",
  },
  {
    id: "loyihalar.item2.4",
    label: "2-loyiha, rasm 5",
    page: "loyihalar",
    block: "2-loyiha",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469212/38_shg9uf.jpg",
  },
  {
    id: "loyihalar.item3.0",
    label: "3-loyiha, rasm 1",
    page: "loyihalar",
    block: "3-loyiha",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469051/photo_2026-04-04_10-35-53_kvt95v.jpg",
  },
  {
    id: "loyihalar.item3.1",
    label: "3-loyiha, rasm 2",
    page: "loyihalar",
    block: "3-loyiha",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469172/20201201_105047_elutha.jpg",
  },
  {
    id: "loyihalar.item3.2",
    label: "3-loyiha, rasm 3",
    page: "loyihalar",
    block: "3-loyiha",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469051/photo_2026-04-04_10-35-50_ctmowh.jpg",
  },
  {
    id: "loyihalar.item3.3",
    label: "3-loyiha, rasm 4",
    page: "loyihalar",
    block: "3-loyiha",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469052/photo_2026-04-04_10-35-55_dvrnxd.jpg",
  },
  {
    id: "loyihalar.item4.0",
    label: "4-loyiha, rasm 1",
    page: "loyihalar",
    block: "4-loyiha",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469047/IMG_5184_%D0%9E%D1%80%D0%B8%D0%B3%D0%B8%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9_%D1%80%D0%B0%D0%B7%D0%BC%D0%B5%D1%80_iuhwco.jpg",
  },
  {
    id: "loyihalar.item4.1",
    label: "4-loyiha, rasm 2",
    page: "loyihalar",
    block: "4-loyiha",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469042/IMG_4545_bl2h6a.jpg",
  },
  {
    id: "loyihalar.item4.2",
    label: "4-loyiha, rasm 3",
    page: "loyihalar",
    block: "4-loyiha",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469038/IMG_4540_2_fhkndi.jpg",
  },
  {
    id: "loyihalar.item4.3",
    label: "4-loyiha, rasm 4",
    page: "loyihalar",
    block: "4-loyiha",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775468985/IMG_4397_copy_iqnrvn.jpg",
  },
  {
    id: "loyihalar.item4.4",
    label: "4-loyiha, rasm 5",
    page: "loyihalar",
    block: "4-loyiha",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469023/IMG_4430_copy_g7mb6k.jpg",
  },
  {
    id: "loyihalar.item5.0",
    label: "5-loyiha, rasm 1",
    page: "loyihalar",
    block: "5-loyiha",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775468983/IMG_4393_copy_g104ol.jpg",
  },
  {
    id: "loyihalar.item5.1",
    label: "5-loyiha, rasm 2",
    page: "loyihalar",
    block: "5-loyiha",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775468989/IMG_3533_zgzdoe.jpg",
  },
  {
    id: "loyihalar.item6.0",
    label: "6-loyiha, rasm 1",
    page: "loyihalar",
    block: "6-loyiha",
    type: "image",
    def: "https://res.cloudinary.com/duvvgqc3i/image/upload/q_auto/f_auto/v1776422634/IMG_1075_rrylu1.jpg",
  },
  {
    id: "loyihalar.item6.1",
    label: "6-loyiha, rasm 2",
    page: "loyihalar",
    block: "6-loyiha",
    type: "image",
    def: "https://res.cloudinary.com/duvvgqc3i/image/upload/q_auto/f_auto/v1776422634/IMG_3535_zs9roq.jpg",
  },
  {
    id: "loyihalar.item6.2",
    label: "6-loyiha, rasm 3",
    page: "loyihalar",
    block: "6-loyiha",
    type: "image",
    def: "https://res.cloudinary.com/duvvgqc3i/image/upload/q_auto/f_auto/v1776422637/IMG_0976_kkvp42.jpg",
  },
  {
    id: "loyihalar.item6.3",
    label: "6-loyiha, rasm 4",
    page: "loyihalar",
    block: "6-loyiha",
    type: "image",
    def: "https://res.cloudinary.com/duvvgqc3i/image/upload/q_auto/f_auto/v1776422634/IMG_1052_qr8w62.jpg",
  },
  {
    id: "loyihalar.item6.4",
    label: "6-loyiha, rasm 5",
    page: "loyihalar",
    block: "6-loyiha",
    type: "image",
    def: "https://res.cloudinary.com/duvvgqc3i/image/upload/q_auto/f_auto/v1776422704/IMG_0980_adj1rq.jpg",
  },
  {
    id: "jixozlar.tech.0",
    label: "Isitish rasmi",
    page: "jixozlar",
    block: "Texnologiya kartalari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775570543/28_bnpx3z.jpg",
  },
  {
    id: "jixozlar.tech.1",
    label: "Ventilyatsiya rasmi",
    page: "jixozlar",
    block: "Texnologiya kartalari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469177/20201023_075858_hcs7fb.jpg",
  },
  {
    id: "jixozlar.tech.2",
    label: "Stellaj rasmi",
    page: "jixozlar",
    block: "Texnologiya kartalari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469181/20201201_105435_hq3q9q.jpg",
  },
  {
    id: "jixozlar.tech.3",
    label: "Sug'orish rasmi",
    page: "jixozlar",
    block: "Texnologiya kartalari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469052/photo_2026-04-04_10-35-55_dvrnxd.jpg",
  },
  {
    id: "jixozlar.tech.4",
    label: "Avtomatlashtirish rasmi",
    page: "jixozlar",
    block: "Texnologiya kartalari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775567811/20201201_125915_z2qls3.jpg",
  },
  {
    id: "issiqxona.vertical.0",
    label: "Vertikal issiqxona, rasm 1",
    page: "issiqxona-turlari",
    block: "Vertikal issiqxona",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1777380061/jfvjhgfhj_msdu7b.png",
  },
  {
    id: "issiqxona.vertical.1",
    label: "Vertikal issiqxona, rasm 2",
    page: "issiqxona-turlari",
    block: "Vertikal issiqxona",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1777380061/Screenshot_21_oy5mp3.png",
  },
  {
    id: "issiqxona.vertical.2",
    label: "Vertikal issiqxona, rasm 3",
    page: "issiqxona-turlari",
    block: "Vertikal issiqxona",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1777380062/Screenshot_20_zmrd8x.png",
  },
  {
    id: "issiqxona.vertical.3",
    label: "Vertikal issiqxona, rasm 4",
    page: "issiqxona-turlari",
    block: "Vertikal issiqxona",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1777380061/jgfgkjjhk_p_pzo1wy.png",
  },
  {
    id: "issiqxona.vertical.4",
    label: "Vertikal issiqxona, rasm 5",
    page: "issiqxona-turlari",
    block: "Vertikal issiqxona",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1777380063/Screenshot_27_xx97id.png",
  },
  {
    id: "issiqxona.vertical.5",
    label: "Vertikal issiqxona, rasm 6",
    page: "issiqxona-turlari",
    block: "Vertikal issiqxona",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1777380062/Screenshot_22_tboyut.png",
  },
  {
    id: "issiqxona.vertical.6",
    label: "Vertikal issiqxona, rasm 7",
    page: "issiqxona-turlari",
    block: "Vertikal issiqxona",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1777380064/Screenshot_88_csxbvo.png",
  },
  {
    id: "issiqxona.mini.0",
    label: "Mini issiqxona, rasm 1",
    page: "issiqxona-turlari",
    block: "Mini issiqxona",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1777378099/photo_3_2026-04-28_17-31-03_zhfpn1.jpg",
  },
  {
    id: "issiqxona.mini.1",
    label: "Mini issiqxona, rasm 2",
    page: "issiqxona-turlari",
    block: "Mini issiqxona",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1777378099/photo_1_2026-04-28_17-31-03_zwupoz.jpg",
  },
  {
    id: "issiqxona.mini.2",
    label: "Mini issiqxona, rasm 3",
    page: "issiqxona-turlari",
    block: "Mini issiqxona",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1777378098/photo_2_2026-04-28_17-31-03_lfnlen.jpg",
  },
  {
    id: "issiqxona.oddiy.0",
    label: "Oddiy issiqxona, rasm 1",
    page: "issiqxona-turlari",
    block: "Oddiy issiqxona",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1777378128/IMG_4542_l2jvtn.jpg",
  },
  {
    id: "issiqxona.oddiy.1",
    label: "Oddiy issiqxona, rasm 2",
    page: "issiqxona-turlari",
    block: "Oddiy issiqxona",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1777378124/IMG_4545_lxx0wp.jpg",
  },
  {
    id: "issiqxona.oddiy.2",
    label: "Oddiy issiqxona, rasm 3",
    page: "issiqxona-turlari",
    block: "Oddiy issiqxona",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1777378098/IMG_4535_glqbmk.jpg",
  },
  {
    id: "issiqxona.oddiy.3",
    label: "Oddiy issiqxona, rasm 4",
    page: "issiqxona-turlari",
    block: "Oddiy issiqxona",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1777378097/IMG_4537_vdhplq.jpg",
  },
  {
    id: "issiqxona.oddiy.4",
    label: "Oddiy issiqxona, rasm 5",
    page: "issiqxona-turlari",
    block: "Oddiy issiqxona",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1777378097/IMG_4536_pgfu4i.jpg",
  },
  {
    id: "issiqxona.gektar.0",
    label: "Gektar issiqxona, rasm 1",
    page: "issiqxona-turlari",
    block: "Gektar issiqxona",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1777378094/IMG_1376_hloucr.jpg",
  },
  {
    id: "issiqxona.gektar.1",
    label: "Gektar issiqxona, rasm 2",
    page: "issiqxona-turlari",
    block: "Gektar issiqxona",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1777378091/IMG_1033_eewztt.jpg",
  },
  {
    id: "issiqxona.gektar.2",
    label: "Gektar issiqxona, rasm 3",
    page: "issiqxona-turlari",
    block: "Gektar issiqxona",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1777378094/IMG_1378_w2cpmq.jpg",
  },
  {
    id: "xalqaro.project.0",
    label: "Loyiha rasmi 1",
    page: "xalqaro",
    block: "Loyiha rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775567811/20201201_125915_z2qls3.jpg",
  },
  {
    id: "xalqaro.project.1",
    label: "Loyiha rasmi 2",
    page: "xalqaro",
    block: "Loyiha rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469052/photo_2026-04-04_10-35-55_dvrnxd.jpg",
  },
  {
    id: "xalqaro.project.2",
    label: "Loyiha rasmi 3",
    page: "xalqaro",
    block: "Loyiha rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775567956/20210211_141225_yvl1wr.jpg",
  },
  {
    id: "xalqaro.project.3",
    label: "Loyiha rasmi 4",
    page: "xalqaro",
    block: "Loyiha rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469181/20201201_105435_hq3q9q.jpg",
  },
  {
    id: "aloqa.background.0",
    label: "Fon slayd 1",
    page: "aloqa",
    block: "Fon rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469052/photo_2026-04-04_10-35-55_dvrnxd.jpg",
  },
  {
    id: "aloqa.background.1",
    label: "Fon slayd 2",
    page: "aloqa",
    block: "Fon rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775567490/20201201_105400_fnjfxf.jpg",
  },
  {
    id: "aloqa.background.2",
    label: "Fon slayd 3",
    page: "aloqa",
    block: "Fon rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775567918/20201201_143010_eudwpq.jpg",
  },
  {
    id: "aloqa.background.3",
    label: "Fon slayd 4",
    page: "aloqa",
    block: "Fon rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775567906/20201201_144821_ojps5y.jpg",
  },
  {
    id: "haqimizda.image",
    label: "Ofis / infografika rasmi",
    page: "haqimizda",
    block: "Rasm",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1776685323/ChatGPT_Image_20_%D0%B0%D0%BF%D1%80._2026_%D0%B3._16_01_12_ckxsni.png",
  },
  {
    id: "gallery.1",
    label: "Sanoat issiqxonasi (№1)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/1.jpg",
  },
  {
    id: "gallery.2",
    label: "Qishloq xo'jaligi issiqxonasi (№2)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/2.jpg",
  },
  {
    id: "gallery.3",
    label: "Quyosh issiqxonasi (№3)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/3.jpg",
  },
  {
    id: "gallery.4",
    label: "Qulupnay issiqxonasi (№4)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/4.jpg",
  },
  {
    id: "gallery.5",
    label: "Raqamli ta'lim markazi (№5)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/7.jpg",
  },
  {
    id: "gallery.6",
    label: "Energetika loyihasi (№6)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/8.jpg",
  },
  {
    id: "gallery.7",
    label: "Eksport issiqxonasi (№7)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/24.jpg",
  },
  {
    id: "gallery.8",
    label: "Gidroponika issiqxonasi (№8)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/25.jpg",
  },
  {
    id: "gallery.9",
    label: "Xalqaro turizm markazi (№9)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/27.jpg",
  },
  {
    id: "gallery.10",
    label: "Prezident tashrifi (№10)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/photo_2026-04-04_10-35-25.jpg",
  },
  {
    id: "gallery.11",
    label: "Loyihalar ochilishi (№11)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/photo_2026-04-04_10-35-29.jpg",
  },
  {
    id: "gallery.12",
    label: "Prezident bilan uchrashuv (№12)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/photo_2026-04-04_10-35-50.jpg",
  },
  {
    id: "gallery.13",
    label: "Memorandum imzolandi (№13)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/photo_2026-04-04_10-35-53.jpg",
  },
  {
    id: "gallery.14",
    label: "Yangi korxona (№14)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/photo_2026-04-04_10-35-54.jpg",
  },
  {
    id: "gallery.15",
    label: "Hududni ko'rish (№15)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/photo_2026-04-04_10-35-55.jpg",
  },
  {
    id: "gallery.21",
    label: "Tomat issiqxonasi (№21)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/5.jpg",
  },
  {
    id: "gallery.22",
    label: "Bodring issiqxonasi (№22)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/6.jpg",
  },
  {
    id: "gallery.23",
    label: "Sabzavot issiqxonasi (№23)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/9.jpg",
  },
  {
    id: "gallery.24",
    label: "Meva issiqxonasi (№24)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/10.jpg",
  },
  {
    id: "gallery.25",
    label: "Gullar issiqxonasi (№25)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/11.jpg",
  },
  {
    id: "gallery.26",
    label: "Ziravorlar issiqxonasi (№26)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/12.jpg",
  },
  {
    id: "gallery.27",
    label: "O'simliklar issiqxonasi (№27)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/13.jpg",
  },
  {
    id: "gallery.28",
    label: "Dorivor o'simliklar issiqxonasi (№28)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/14.jpg",
  },
  {
    id: "gallery.29",
    label: "Tibbiy o'simliklar issiqxonasi (№29)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/15.jpg",
  },
  {
    id: "gallery.30",
    label: "Organik issiqxona (№30)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "/images/16.jpg",
  },
  {
    id: "gallery.31",
    label: "Qozog'iston loyihasi (№31)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469176/20201201_105259_q5us00.jpg",
  },
  {
    id: "gallery.32",
    label: "Tojikiston loyihasi (№32)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469052/photo_2026-04-04_10-35-55_dvrnxd.jpg",
  },
  {
    id: "gallery.33",
    label: "Qirg'iziston loyihasi (№33)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775567956/20210211_141225_yvl1wr.jpg",
  },
  {
    id: "gallery.34",
    label: "Turkmaniston loyihasi (№34)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469052/IMG_5193_%D0%9E%D1%80%D0%B8%D0%B3%D0%B8%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9_%D1%80%D0%B0%D0%B7%D0%BC%D0%B5%D1%80_rmwd8l.jpg",
  },
  {
    id: "gallery.35",
    label: "Isitish tizimi (№35)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775570543/28_bnpx3z.jpg",
  },
  {
    id: "gallery.36",
    label: "Ventilyatsiya (№36)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469177/20201023_075858_hcs7fb.jpg",
  },
  {
    id: "gallery.37",
    label: "Stelaj tizimi (№37)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469181/20201201_105435_hq3q9q.jpg",
  },
  {
    id: "gallery.38",
    label: "Avtomatlashtirish (№38)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775567811/20201201_125915_z2qls3.jpg",
  },
  {
    id: "gallery.39",
    label: "Andijon loyihasi 1 (№39)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775468970/21_bv62xg.jpg",
  },
  {
    id: "gallery.40",
    label: "Andijon loyihasi 2 (№40)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775301447/22_qrawq5.jpg",
  },
  {
    id: "gallery.41",
    label: "Andijon loyihasi 3 (№41)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469214/34_rthdcs.jpg",
  },
  {
    id: "gallery.42",
    label: "Andijon loyihasi 4 (№42)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469212/32_2_n7x8lw.jpg",
  },
  {
    id: "gallery.43",
    label: "Andijon loyihasi 5 (№43)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469212/38_shg9uf.jpg",
  },
  {
    id: "gallery.44",
    label: "Samarqand loyihasi 1 (№44)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469051/photo_2026-04-04_10-35-53_kvt95v.jpg",
  },
  {
    id: "gallery.45",
    label: "Samarqand loyihasi 2 (№45)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/dnqi0bdjk/image/upload/v1775469172/20201201_105047_elutha.jpg",
  },
  {
    id: "gallery.46",
    label: "Yangi loyiha (№46)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/duvvgqc3i/image/upload/q_auto/f_auto/v1776422619/IMG_1015_jf5dqm.jpg",
  },
  {
    id: "gallery.47",
    label: "Yangi loyiha (№47)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/duvvgqc3i/image/upload/q_auto/f_auto/v1776422624/IMG_0994_angy5l.jpg",
  },
  {
    id: "gallery.48",
    label: "Yangi loyiha (№48)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/duvvgqc3i/image/upload/q_auto/f_auto/v1776422625/IMG_1033_akpcc1.jpg",
  },
  {
    id: "gallery.49",
    label: "Yangi loyiha (№49)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/duvvgqc3i/image/upload/q_auto/f_auto/v1776422625/IMG_1030_dcuj82.jpg",
  },
  {
    id: "gallery.50",
    label: "Yangi loyiha (№50)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/duvvgqc3i/image/upload/q_auto/f_auto/v1776422629/IMG_1001_vft7io.jpg",
  },
  {
    id: "gallery.51",
    label: "Yangi loyiha (№51)",
    page: "gallery",
    block: "Galereya rasmlari",
    type: "image",
    def: "https://res.cloudinary.com/duvvgqc3i/image/upload/q_auto/f_auto/v1776422629/IMG_1059_wwp8bn.jpg",
  },
];

export const MEDIA_DEFAULTS: Record<string, string> = Object.fromEntries(
  MEDIA.map((item) => [item.id, item.def]),
);
